version: "3"

services:
  web:
    build: .
    env_file:
      - .env/local/django
    networks:
      - menu-vote_postgres
      - default
    volumes:
      - .:/app
      - ./media:/app/media
    command: >
      bash -c "./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"


networks:
  menu-vote_postgres:
    external: true
