apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-container
  template:
    metadata:
      labels:
        app: django-container
    spec:
      containers:
        - name: django
          volumeMounts:
            - name: media-volume
              mountPath: /app/media
          image: alig1493/menu_vote:latest
          command: ["/bin/bash", "-c", "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"] # runs migrations and starts the server
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: postgres
            - secretRef:
                name: django
      volumes:
        - name: media-volume
          hostPath:
            path: /Users/ali/work_stash/menu-votes/media